const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const today=new Date();
const iso=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);
const plus=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const storeKey="malagasycarDemo";
const emptyData={rentals:[],trips:[],payments:[]};
const getData=()=>{try{return {...emptyData,...JSON.parse(localStorage.getItem(storeKey)||"{}")}}catch{return {...emptyData}}};
const saveData=d=>localStorage.setItem(storeKey,JSON.stringify(d));
function toast(msg){let t=$("#toast");if(!t){t=document.createElement("div");t.id="toast";t.className="toast";document.body.appendChild(t)}t.textContent=msg;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),3200)}
function dateOverlap(a,b,c,d){return new Date(a)<new Date(d)&&new Date(b)>new Date(c)}
function daysBetween(a,b){if(!a||!b)return 0;return Math.max(0,Math.ceil((new Date(b)-new Date(a))/86400000))}
function rentalState(car,start,end){const d=getData();const hits=d.rentals.filter(r=>r.car===car&&r.status!=="CANCELLED"&&dateOverlap(start,end,r.start,r.end));if(hits.some(r=>r.status==="CONFIRMED"))return "CONFIRMED";if(hits.some(r=>r.status==="PENDING_PAYMENT"))return "PENDING_PAYMENT";return "AVAILABLE"}
function rentalBusy(car,start,end){return rentalState(car,start,end)!=="AVAILABLE"}
function rentalRate(car){if(car.includes("RAV4"))return 260000;if(car.includes("Starex"))return 320000;if(car.includes("Hiace"))return 380000;return 180000}
function initRentalFilters(){$$(".rental-filter").forEach(btn=>btn.onclick=()=>{$$(".rental-filter").forEach(x=>x.classList.remove("active"));btn.classList.add("active");const type=btn.dataset.filter;$$(".car-card").forEach(card=>{card.style.display=type==="all"||card.dataset.type===type?"":"none"})})}
function statusLabel(s){return ({PENDING_PAYMENT:"En attente",CONFIRMED:"Confirmée",CANCELLED:"Annulée",PENDING:"À valider",VALIDATED:"Validé"}[s]||s)}
function statusClass(s){return s==="CONFIRMED"||s==="VALIDATED"?"ok":s==="CANCELLED"?"cancel":s==="PENDING_PAYMENT"||s==="PENDING"?"wait":"blue"}
function initTabs(){$$(".booking-tab").forEach(b=>b.onclick=()=>{$$(".booking-tab").forEach(x=>x.classList.remove("active"));$$(".booking-panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");$("#"+b.dataset.tab+"-panel")?.classList.add("active")})}
initTabs();
initRentalFilters();
const travelDate=$("#travel-date");if(travelDate)travelDate.value=iso(plus(today,1));
const rs=$("#rental-start"),re=$("#rental-end");if(rs){rs.value=iso(plus(today,1));if(re)re.value=iso(plus(today,4))}
$("#search-travel")?.addEventListener("click",()=>location.href="reservation.html?type=travel");
$("#search-rental")?.addEventListener("click",()=>location.href="reservation.html?type=rental");
if($("#rental-catalog")){
  function refresh(){$$("#rental-catalog .car-card").forEach(card=>{const state=rentalState(card.dataset.car,rs?.value,re?.value);const badge=$(".badge",card),btn=$(".rent",card);const map={AVAILABLE:["● Disponible","available","Réserver"],PENDING_PAYMENT:["● En attente","pending","En attente"],CONFIRMED:["● Indisponible","unavailable","Indisponible"]};const [txt,cls,label]=map[state];badge.textContent=txt;badge.className="badge "+cls;btn.disabled=state!=="AVAILABLE";btn.style.opacity=state!=="AVAILABLE"?.45:1;btn.textContent=label})}
  rs?.addEventListener("change",refresh);re?.addEventListener("change",refresh);refresh();
}
$$(".rent").forEach(btn=>btn.onclick=()=>{const card=btn.closest(".car-card"),start=rs?.value||iso(plus(today,1)),end=re?.value||iso(plus(today,4));if(rentalBusy(card.dataset.car,start,end)){toast("Ce véhicule n'est pas disponible sur cette période.");return}location.href=`reservation.html?type=rental&car=${encodeURIComponent(card.dataset.car)}&start=${start}&end=${end}`});
if($("#reservation-app")){
  const params=new URLSearchParams(location.search),type=params.get("type")||"travel",car=params.get("car")||"Toyota Corolla";
  if(type==="rental"){$("#travel-step")?.classList.add("hidden");$("#rental-step")?.classList.remove("hidden");$("#booking-kind").textContent="Location de voiture";$("#car-name").textContent=car;const s=$("#r-start"),e=$("#r-end");s.value=params.get("start")||iso(plus(today,1));e.value=params.get("end")||iso(plus(today,4))}else{$("#travel-step")?.classList.remove("hidden");$("#rental-step")?.classList.add("hidden")}
  let selectedSeat=null;const occupied=[2,5],seatGrid=$("#seats");
  if(seatGrid)for(let i=2;i<=7;i++){const b=document.createElement("button");b.type="button";b.className="seat"+(occupied.includes(i)?" busy":"");b.textContent=String(i).padStart(2,"0");if(!occupied.includes(i))b.onclick=()=>{$$(".seat",seatGrid).forEach(x=>x.classList.remove("selected"));b.classList.add("selected");selectedSeat=i;$("#seat-value").textContent=String(i).padStart(2,"0")};seatGrid.appendChild(b)}
  function rentalCalc(){const s=$("#r-start")?.value,e=$("#r-end")?.value,n=daysBetween(s,e),price=car.includes("RAV4")?260000:car.includes("Minibus")?420000:180000;$("#r-days")&&($("#r-days").textContent=n+" jour(s)",$("#r-total").textContent=(n*price).toLocaleString("fr-FR")+" Ar");return[n,price]}
  $("#r-start")?.addEventListener("change",rentalCalc);$("#r-end")?.addEventListener("change",rentalCalc);rentalCalc();
  let travelTicket=null;
  function formatTravelDate(value){if(!value)return"—";return new Date(value+"T12:00:00").toLocaleDateString("fr-FR",{day:"2-digit",month:"2-digit",year:"numeric"})}
  function makeTicket(){const d=new Date();const stamp=d.getFullYear().toString().slice(-2)+String(d.getMonth()+1).padStart(2,"0")+String(d.getDate()).padStart(2,"0");return "MGC-"+stamp+"-"+Math.floor(1000+Math.random()*9000)}
  function openTravelRecap(){const name=$("#t-name")?.value.trim(),phone=$("#t-phone")?.value.trim();if(!name){toast("Veuillez renseigner le nom du client.");$("#t-name")?.focus();return}if(!phone){toast("Veuillez renseigner le numéro de téléphone.");$("#t-phone")?.focus();return}travelTicket=travelTicket||makeTicket();const total=180000,deposit=Math.round(total*.50);$("#recap-departure").textContent="Antananarivo";$("#recap-arrival").textContent="Mahajanga";$("#recap-name").textContent=name;$("#recap-phone").textContent=phone;$("#recap-date").textContent=formatTravelDate(travelDate?.value||iso(plus(today,1)));$("#recap-seat").textContent=String(selectedSeat).padStart(2,"0");$("#recap-ticket").textContent=travelTicket;$("#recap-total").textContent=total.toLocaleString("fr-FR")+" Ar";$("#recap-percent").textContent="50 %";$("#recap-deposit").textContent=deposit.toLocaleString("fr-FR")+" Ar";$("#recap-balance").textContent=(total-deposit).toLocaleString("fr-FR")+" Ar";$("#travel-modal")?.classList.remove("hidden");$("#travel-modal")?.setAttribute("aria-hidden","false")}
  function closeTravelRecap(){$("#travel-modal")?.classList.add("hidden");$("#travel-modal")?.setAttribute("aria-hidden","true")}
  if($("#travel-modal")){$("#travel-modal").querySelectorAll("[data-close-modal]").forEach(el=>el.addEventListener("click",closeTravelRecap));$("#edit-travel")?.addEventListener("click",closeTravelRecap)}
  $("#continue-travel")?.addEventListener("click",()=>{if(!selectedSeat){toast("Sélectionnez un siège.");return}$("#traveler-form")?.classList.remove("hidden");$("#traveler-placeholder")?.classList.add("hidden");$("#travel-summary").textContent="Siège "+String(selectedSeat).padStart(2,"0")+" sélectionné — renseignez vos coordonnées puis affichez le récapitulatif."});
  $("#continue-rental")?.addEventListener("click",()=>{const[n]=rentalCalc(),start=$("#r-start").value,end=$("#r-end").value;if(n<=0||new Date(end)<=new Date(start)){toast("Dates invalides.");return}if(rentalBusy(car,start,end)){toast("Cette voiture n'est plus disponible sur cette période.");return}$("#rental-form")?.classList.remove("hidden");$("#rental-placeholder")?.classList.add("hidden")});
  $("#pay-travel")?.addEventListener("click",openTravelRecap);
  $("#confirm-travel-payment")?.addEventListener("click",()=>{closeTravelRecap();completeBooking("TRAVEL")});
  $("#pay-rental")?.addEventListener("click",()=>completeBooking("RENTAL"));
  function completeBooking(kind){const data=getData(),id="MLC-"+Date.now().toString().slice(-7);if(kind==="RENTAL"){const start=$("#r-start").value,end=$("#r-end").value;if(rentalBusy(car,start,end)){toast("Cette voiture vient d'être réservée.");return}const rental={id,car,start,end,status:"PENDING_PAYMENT",customer:$("#r-name").value||"Client démo",amount:$("#r-total").textContent};data.rentals.push(rental);data.payments.push({id,type:"Location",status:"PENDING",amount:rental.amount,linkedType:"rental"});saveData(data);$("#success")?.classList.remove("hidden");$("#success").querySelector("h2").textContent="✓ Demande de location enregistrée";$("#success").querySelector("p").textContent="Votre paiement est en attente de validation par l'administration. La voiture sera marquée indisponible dès validation."}else{const total=180000,deposit=Math.round(total*.50),name=$("#t-name").value.trim()||"Client démo",phone=$("#t-phone").value.trim()||"—";const ticket=travelTicket||makeTicket();const trip={id,ticket,route:"Antananarivo → Mahajanga",departure:"Antananarivo",arrival:"Mahajanga",date:travelDate?.value||iso(plus(today,1)),seat:selectedSeat,status:"PENDING_PAYMENT",customer:name,phone,totalAmount:total,depositPercent:50,amountDue:deposit};data.trips.push(trip);data.payments.push({id,type:"Voyage",status:"PENDING",amount:deposit.toLocaleString("fr-FR")+" Ar",totalAmount:total,depositPercent:50,linkedType:"trip"});saveData(data);$("#success")?.classList.remove("hidden");$("#success").querySelector("h2").textContent="✓ Réservation enregistrée";$("#success").querySelector("p").textContent="Ticket "+ticket+" · Acompte de 50 % : "+deposit.toLocaleString("fr-FR")+" Ar. Le paiement est en attente de validation par l'administration."}$("#success-id").textContent=id;window.scrollTo({top:0,behavior:"smooth"});toast("Demande enregistrée. Paiement à valider.")}
}
if($("#admin-app")){
  const fleet=[{name:"Toyota Hiace",cat:"CAR"},{name:"Hyundai Starex 7 places",cat:"MINIBUS · 7 places"},{name:"Toyota RAV4",cat:"4×4"},{name:"Toyota Corolla",cat:"Voiture légère"}];
  function renderAdmin(){const d=getData(),confirmed=d.rentals.filter(x=>x.status==="CONFIRMED");$("#kpi-res").textContent=d.rentals.length+d.trips.length;$("#kpi-pay").textContent=d.payments.filter(x=>x.status==="PENDING").length;$("#kpi-rent").textContent=confirmed.length;$("#kpi-cars").textContent=fleet.length-confirmed.filter(x=>dateOverlap(iso(today),iso(plus(today,1)),x.start,x.end)).length;const rows=[...d.rentals.map(r=>({id:r.id,kind:"Location",item:r.car,date:r.start+" → "+r.end,status:r.status,amount:r.amount,rental:true})),...d.trips.map(t=>({id:t.id,kind:"Voyage",item:t.route,date:t.date,status:t.status,amount:"180 000 Ar",rental:false}))];$("#reservation-rows").innerHTML=rows.length?rows.map(r=>`<tr><td>${r.id}</td><td>${r.kind}</td><td>${r.item}</td><td>${r.date}</td><td><span class="status ${statusClass(r.status)}">${statusLabel(r.status)}</span></td><td>${r.amount}</td><td>${r.rental&&r.status!=="CANCELLED"?`<button class="btn btn-sm btn-danger" onclick="cancelRental('${r.id}')">Annuler</button>`:"—"}</td></tr>`).join(""):`<tr><td colspan="7">Aucune réservation de démonstration.</td></tr>`;$("#payment-rows").innerHTML=d.payments.length?d.payments.map(p=>`<tr><td>${p.id}</td><td>${p.type}</td><td>${p.amount}</td><td><span class="status ${statusClass(p.status)}">${statusLabel(p.status)}</span></td><td>${p.status==="PENDING"?`<button class="btn btn-sm btn-primary" onclick="validatePayment('${p.id}')">Valider</button>`:"—"}</td></tr>`).join(""):`<tr><td colspan="5">Aucun paiement.</td></tr>`;$("#fleet-rows").innerHTML=fleet.map(v=>{const active=d.rentals.find(r=>r.car===v.name&&r.status!=="CANCELLED"&&dateOverlap(iso(today),iso(plus(today,1)),r.start,r.end));const cls=active?.status==="CONFIRMED"?"unavailable":active?.status==="PENDING_PAYMENT"?"pending":"available";const label=active?.status==="CONFIRMED"?"Indisponible":active?.status==="PENDING_PAYMENT"?"En attente":"Disponible";return `<tr><td>${v.name}</td><td>${v.cat}</td><td><span class="status ${cls==='available'?'ok':cls==='pending'?'wait':'cancel'}">${label}</span></td><td>${active?active.id:"—"}</td></tr>`}).join("");buildCalendar()}
  window.validatePayment=id=>{const d=getData(),p=d.payments.find(x=>x.id===id);if(!p||p.status!=="PENDING")return;p.status="VALIDATED";if(p.linkedType==="rental"){const r=d.rentals.find(x=>x.id===id);if(r)r.status="CONFIRMED"}if(p.linkedType==="trip"){const t=d.trips.find(x=>x.id===id);if(t)t.status="CONFIRMED"}saveData(d);renderAdmin();toast("Paiement validé. La réservation est confirmée.")};
  window.cancelRental=id=>{const d=getData(),r=d.rentals.find(x=>x.id===id);if(!r)return;r.status="CANCELLED";const p=d.payments.find(x=>x.id===id);if(p&&p.status==="PENDING")p.status="CANCELLED";saveData(d);renderAdmin();toast("Location annulée. Le véhicule est de nouveau disponible.")};
  function buildCalendar(){const start=new Date(today.getFullYear(),today.getMonth(),1),days=[];for(let i=0;i<35;i++)days.push(plus(start,i));const d=getData();$("#admin-cal").innerHTML=["Lun","Mar","Mer","Jeu","Ven","Sam","Dim"].map(x=>`<div class="cal-head">${x}</div>`).join("")+days.map(day=>{const busy=d.rentals.filter(r=>r.status!=="CANCELLED"&&dateOverlap(iso(day),iso(plus(day,1)),r.start,r.end));return `<div class="cal-day ${iso(day)===iso(today)?"today":""}"><b>${day.getDate()}</b>${busy.slice(0,3).map(r=>`<small class="${r.status==="CONFIRMED"?"r":"wait"}">${r.car}${r.status==="PENDING_PAYMENT"?" · attente":""}</small>`).join("")}${busy.length===0?'<small class="a">Disponible</small>':""}</div>`}).join("")}
  renderAdmin();
}
if($("#contact-form"))$("#contact-form").onsubmit=e=>{e.preventDefault();toast("Message envoyé — démonstration.");e.target.reset()};
$$('.menu').forEach(m=>m.onclick=()=>$(".navlinks")?.classList.toggle("open"));